#Array Manipulation Routines

In [2]:
import numpy as np
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [3]:
y=x.reshape((3,2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [4]:
#Create a 2d array
x=np.array([[0,1,2],[3,4,5]],dtype=np.uint8)
print(x)

[[0 1 2]
 [3 4 5]]


In [5]:
y = np.reshape(x,6)
print(y)

[0 1 2 3 4 5]


In [6]:
#another method to reshape
y = np.ravel(x)
print(y)

[0 1 2 3 4 5]


In [7]:
print(x)

[[0 1 2]
 [3 4 5]]


In [10]:
#another way
y=x.flatten()
print(y)

[0 1 2 3 4 5]


In [11]:
#column wise flattening
y=x.flatten('F')
print(y)

[0 3 1 4 2 5]


In [12]:
#row wise flattening
y=x.flatten('C')
print(y)

[0 1 2 3 4 5]


In [14]:
x = np.array([1,2,3],dtype=np.uint8)
y = np.array([4,5,6],dtype=np.uint8)
print(x.dtype)
print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


In [15]:
#To join 2 arrays
z=np.stack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [16]:
#To join 2 arrays
z=np.stack((x,y),axis=0)
print(z)

[[1 2 3]
 [4 5 6]]


In [17]:
#To join 2 arrays
z=np.stack((x,y),axis=-1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [18]:
print(x)
print(y)

[1 2 3]
[4 5 6]


In [19]:
#other stack operations
z=np.dstack((x,y))
print(z)

[[[1 4]
  [2 5]
  [3 6]]]


In [20]:
#other stack operations
z=np.hstack((x,y))
print(z)

[1 2 3 4 5 6]


In [21]:
#other stack operations
z=np.vstack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [22]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [23]:
#to split x into 3 different arrays
a,b,c = np.split(x,3)
print(a,b,c)

[0 1 2] [3 4 5] [6 7 8]


In [24]:
x=np.random.rand(4,4,4)
print(x)

[[[6.85883145e-01 6.36820497e-01 8.15953581e-01 4.11967380e-01]
  [6.51294588e-01 6.80847624e-01 9.36497961e-01 8.67239491e-01]
  [8.56371002e-01 9.14120794e-01 1.57485319e-01 6.01672199e-01]
  [7.22880235e-01 4.73981913e-01 1.07165080e-01 7.00859868e-01]]

 [[8.13460786e-01 1.93107208e-01 4.93436189e-01 4.66505706e-01]
  [8.72347280e-01 3.14413891e-01 8.75017486e-01 6.80652100e-02]
  [4.86933566e-04 1.28928206e-01 4.28343093e-01 4.68709323e-01]
  [1.85600986e-01 5.27861679e-01 6.26356691e-01 6.33563165e-01]]

 [[6.30180590e-01 5.76344991e-02 9.47417945e-01 6.81906011e-01]
  [1.87279569e-01 8.54759033e-02 2.43961149e-01 2.92049469e-01]
  [2.53844795e-01 3.19978343e-01 4.06874605e-01 9.36952941e-01]
  [1.39622065e-01 7.69163758e-01 1.85985508e-01 2.71813553e-01]]

 [[5.37710696e-01 5.26060084e-02 6.93603286e-01 4.92586015e-01]
  [4.73673836e-01 4.67686723e-01 7.69410107e-01 4.02592007e-02]
  [4.35442319e-01 5.50674520e-01 7.99110723e-02 5.39628922e-02]
  [5.84389092e-01 3.38374166e-01 4

In [25]:
y,z = np.split(x,2)
print(y,z)

[[[6.85883145e-01 6.36820497e-01 8.15953581e-01 4.11967380e-01]
  [6.51294588e-01 6.80847624e-01 9.36497961e-01 8.67239491e-01]
  [8.56371002e-01 9.14120794e-01 1.57485319e-01 6.01672199e-01]
  [7.22880235e-01 4.73981913e-01 1.07165080e-01 7.00859868e-01]]

 [[8.13460786e-01 1.93107208e-01 4.93436189e-01 4.66505706e-01]
  [8.72347280e-01 3.14413891e-01 8.75017486e-01 6.80652100e-02]
  [4.86933566e-04 1.28928206e-01 4.28343093e-01 4.68709323e-01]
  [1.85600986e-01 5.27861679e-01 6.26356691e-01 6.33563165e-01]]] [[[0.63018059 0.0576345  0.94741795 0.68190601]
  [0.18727957 0.0854759  0.24396115 0.29204947]
  [0.25384479 0.31997834 0.40687461 0.93695294]
  [0.13962207 0.76916376 0.18598551 0.27181355]]

 [[0.5377107  0.05260601 0.69360329 0.49258602]
  [0.47367384 0.46768672 0.76941011 0.0402592 ]
  [0.43544232 0.55067452 0.07991107 0.05396289]
  [0.58438909 0.33837417 0.46863166 0.66944918]]]


In [26]:
y,z = np.dsplit(x,2)
print(y,z)

[[[6.85883145e-01 6.36820497e-01]
  [6.51294588e-01 6.80847624e-01]
  [8.56371002e-01 9.14120794e-01]
  [7.22880235e-01 4.73981913e-01]]

 [[8.13460786e-01 1.93107208e-01]
  [8.72347280e-01 3.14413891e-01]
  [4.86933566e-04 1.28928206e-01]
  [1.85600986e-01 5.27861679e-01]]

 [[6.30180590e-01 5.76344991e-02]
  [1.87279569e-01 8.54759033e-02]
  [2.53844795e-01 3.19978343e-01]
  [1.39622065e-01 7.69163758e-01]]

 [[5.37710696e-01 5.26060084e-02]
  [4.73673836e-01 4.67686723e-01]
  [4.35442319e-01 5.50674520e-01]
  [5.84389092e-01 3.38374166e-01]]] [[[0.81595358 0.41196738]
  [0.93649796 0.86723949]
  [0.15748532 0.6016722 ]
  [0.10716508 0.70085987]]

 [[0.49343619 0.46650571]
  [0.87501749 0.06806521]
  [0.42834309 0.46870932]
  [0.62635669 0.63356316]]

 [[0.94741795 0.68190601]
  [0.24396115 0.29204947]
  [0.40687461 0.93695294]
  [0.18598551 0.27181355]]

 [[0.69360329 0.49258602]
  [0.76941011 0.0402592 ]
  [0.07991107 0.05396289]
  [0.46863166 0.66944918]]]


In [27]:
y,z = np.hsplit(x,2)
print(y,z)

[[[0.68588314 0.6368205  0.81595358 0.41196738]
  [0.65129459 0.68084762 0.93649796 0.86723949]]

 [[0.81346079 0.19310721 0.49343619 0.46650571]
  [0.87234728 0.31441389 0.87501749 0.06806521]]

 [[0.63018059 0.0576345  0.94741795 0.68190601]
  [0.18727957 0.0854759  0.24396115 0.29204947]]

 [[0.5377107  0.05260601 0.69360329 0.49258602]
  [0.47367384 0.46768672 0.76941011 0.0402592 ]]] [[[8.56371002e-01 9.14120794e-01 1.57485319e-01 6.01672199e-01]
  [7.22880235e-01 4.73981913e-01 1.07165080e-01 7.00859868e-01]]

 [[4.86933566e-04 1.28928206e-01 4.28343093e-01 4.68709323e-01]
  [1.85600986e-01 5.27861679e-01 6.26356691e-01 6.33563165e-01]]

 [[2.53844795e-01 3.19978343e-01 4.06874605e-01 9.36952941e-01]
  [1.39622065e-01 7.69163758e-01 1.85985508e-01 2.71813553e-01]]

 [[4.35442319e-01 5.50674520e-01 7.99110723e-02 5.39628922e-02]
  [5.84389092e-01 3.38374166e-01 4.68631661e-01 6.69449177e-01]]]


In [28]:
y,z = np.vsplit(x,2)
print(y,z)

[[[6.85883145e-01 6.36820497e-01 8.15953581e-01 4.11967380e-01]
  [6.51294588e-01 6.80847624e-01 9.36497961e-01 8.67239491e-01]
  [8.56371002e-01 9.14120794e-01 1.57485319e-01 6.01672199e-01]
  [7.22880235e-01 4.73981913e-01 1.07165080e-01 7.00859868e-01]]

 [[8.13460786e-01 1.93107208e-01 4.93436189e-01 4.66505706e-01]
  [8.72347280e-01 3.14413891e-01 8.75017486e-01 6.80652100e-02]
  [4.86933566e-04 1.28928206e-01 4.28343093e-01 4.68709323e-01]
  [1.85600986e-01 5.27861679e-01 6.26356691e-01 6.33563165e-01]]] [[[0.63018059 0.0576345  0.94741795 0.68190601]
  [0.18727957 0.0854759  0.24396115 0.29204947]
  [0.25384479 0.31997834 0.40687461 0.93695294]
  [0.13962207 0.76916376 0.18598551 0.27181355]]

 [[0.5377107  0.05260601 0.69360329 0.49258602]
  [0.47367384 0.46768672 0.76941011 0.0402592 ]
  [0.43544232 0.55067452 0.07991107 0.05396289]
  [0.58438909 0.33837417 0.46863166 0.66944918]]]


In [29]:
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [31]:
#to check the flip function
y = np.flip(x,axis=-1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [32]:
#to check the flip function
y = np.flip(x,axis=-0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [33]:
#to check the flip function
y = np.flip(x,axis=1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [34]:
#another flip function : fliplr flip left to right
y = np.fliplr(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [35]:
#another flip function : fliplr flip updown
y = np.flipud(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [38]:
#roll function : below === shift last 8 with first 8=====shift it by 8 and then check as linear array
y = np.roll(x,8)
print(y)

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [39]:
#rotation
y =np.rot90(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
