In [1]:
import numpy as np

In [2]:
#Will generate array of size 10 with lower bound 0 and upper bound 9
x = np.random.randint(low=0,high=9,size=10)
print(x)

[1 7 5 0 0 2 0 7 2 7]


In [3]:
x = np.random.randint(low=0,high=9,size=10)
print(x)

[8 6 3 6 3 2 3 5 4 4]


In [4]:
x = np.random.randint(low=0,high=9,size=10)
print(x)

[7 0 0 6 3 2 4 3 7 3]


In [5]:
#to generate matrix of size with random values
x=np.random.rand(3,3)
print(x)

[[0.49941984 0.24123977 0.19789707]
 [0.45693266 0.15545838 0.43136696]
 [0.38094573 0.17114829 0.58897776]]


In [6]:
x=np.random.rand(3,3,3)
print(x)

[[[0.82031112 0.32195649 0.61800452]
  [0.66889296 0.49444964 0.28673149]
  [0.66677739 0.61711196 0.45992198]]

 [[0.17318432 0.86778268 0.9134226 ]
  [0.52873928 0.816186   0.13559207]
  [0.91694381 0.60229061 0.98954533]]

 [[0.16944089 0.64283658 0.74138673]
  [0.34189448 0.05598556 0.75858741]
  [0.26235961 0.35249911 0.20256174]]]
