#Ones and Zeros

In [8]:
import numpy as np
#create empty array and initialize it with random elements
x = print(np.empty([3,3],np.uint8))
#create array where diagonal elements are 1 and k=1 shifts the diagonal upwards
y = print(np.eye(5,dtype=np.uint8,k=1))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [9]:
#create identity matrix
x =print(np.identity(5,dtype=np.uint8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [11]:
#create an a 3d matrix of ones
x = print(np.ones((2,5,5),dtype=np.int16))

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [12]:
#create an a 3d matrix of zeros
x = print(np.zeros((2,5,5),dtype=np.int16))

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [18]:
#create an a 3d matrix of size and fill it with a specific value
x = print(np.full((3,3,3),dtype=np.int16,fill_value=5))

[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]


#Matrix Creation Routines

In [24]:
#lower triangle elements 1 and diagonal shifting based on the value of k
x = print(np.tri(5,5,k=0,dtype=np.uint16))
y = print(np.tri(5,5,k=1,dtype=np.uint16))
z = print(np.tri(5,5,k=-1,dtype=np.uint16))

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]
[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [26]:
x = np.ones((5,5),dtype=np.uint8)
y = np.triu(x,k=0)
print(y)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


In [27]:
x = np.ones((5,5),dtype=np.uint8)
y = np.tril(x,k=0)
print(y)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]
